// src/services/gameData.js
// Mock data with Supabase-ready structure

export const MOCK_ARTICLES = [
  {
    id: '1',
    title: 'eFootball 2025 Season 5: New Legendary Players & Massive Updates',
    slug: 'efootball-2025-season-5-legendary-players',
    excerpt: 'Konami drops the biggest update of the year with 12 new Iconic Moment players, revamped Matchday events, and a complete stadium overhaul.',
    content: `Konami has officially launched Season 5 of eFootball 2025, bringing with it a wave of content that has the community buzzing with excitement. The highlight of this update is the addition of 12 new Iconic Moment players, including long-awaited legends from South American football.

The new Matchday format introduces weekly themed events where players can earn exclusive Gacha tickets simply by completing in-game challenges. The stadium system has also received a complete visual overhaul, with 8 new arenas added to the roster.

**Key Changes in Season 5:**
- 12 new Iconic Moment players including Ronaldinho, Zidane, and Maldini peak forms
- Revamped Matchday events with better rewards structure  
- 8 new stadiums with enhanced crowd animations
- Ball physics engine v3.0 with improved dribbling response
- New team press tactics system
- Division Rivals matchmaking improvements

The update also addresses numerous community complaints about the AI behavior in challenge matches, with Konami stating they've implemented 200+ individual fixes to the match engine.`,
    category: 'eFootball News',
    author: 'GameZ Editor',
    author_avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=editor1',
    published_at: '2026-06-20T10:00:00Z',
    thumbnail: '/efootball-thumb.png',
    read_time: 5,
    views: 12400,
    tags: ['eFootball', 'Season 5', 'Update', 'Legendary Players'],
    featured: true,
  },
  {
    id: '2',
    title: 'eFootball Coins Guide 2025: Best Ways to Earn Without Spending',
    slug: 'efootball-coins-guide-2025-earn-free',
    excerpt: 'Complete guide to maximizing your eFootball coin income through daily login bonuses, challenge rewards, and event participation strategies.',
    content: 'Full guide content here...',
    category: 'eFootball News',
    author: 'ProGamer99',
    author_avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=pro99',
    published_at: '2026-06-18T14:00:00Z',
    thumbnail: '/efootball-thumb.png',
    read_time: 8,
    views: 8700,
    tags: ['eFootball', 'Coins', 'Guide', 'Free2Play'],
    featured: false,
  },
  {
    id: '3',
    title: 'Top 10 eFootball Players to Build Around in Division 1',
    slug: 'top-10-efootball-players-division-1',
    excerpt: 'Our expert analysis reveals the most impactful player cards for climbing Division Rivals in the current meta.',
    content: 'Full article content...',
    category: 'eFootball News',
    author: 'TacticsMaster',
    author_avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=tactics',
    published_at: '2026-06-15T09:00:00Z',
    thumbnail: '/efootball-thumb.png',
    read_time: 6,
    views: 15200,
    tags: ['eFootball', 'Meta', 'Division 1', 'Best Players'],
    featured: false,
  },
  {
    id: '4',
    title: 'PUBG Season 32 Map Rotation: What to Expect This Month',
    slug: 'pubg-season-32-map-rotation',
    excerpt: 'Season 32 brings back the fan-favorite Sanhok to ranked, while Taego gets a major environmental rework with destructible terrain.',
    content: `PUBG Corp has announced the full details of Season 32's map rotation and major environmental updates. The most exciting news is the return of Sanhok to the ranked playlist after a 2-season absence, alongside a massive rework of the Taego map.

**Season 32 Highlights:**
- Sanhok returns to Ranked queue
- Taego receives destructible terrain system  
- New vehicle: Armored BRDM-2 with mounted MG
- Updated blue zone mechanics for faster end-game
- New parachute skins and emotes
- Anti-cheat system v5 deployment

The Taego rework introduces destructible building walls, allowing players to create new sightlines and entry points. This fundamentally changes how the meta-game plays out in the late circle.`,
    category: 'PUBG News',
    author: 'BattleZone',
    author_avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=battlezone',
    published_at: '2026-06-19T12:00:00Z',
    thumbnail: '/pubg-thumb.png',
    read_time: 4,
    views: 21000,
    tags: ['PUBG', 'Season 32', 'Map Rotation', 'Sanhok'],
    featured: true,
  },
  {
    id: '5',
    title: 'PUBG Pro Tips: Winning Chicken Dinners in Season 32',
    slug: 'pubg-pro-tips-season-32-chicken-dinner',
    excerpt: 'Top-ranked players share their strategies for dominating the updated map rotation and securing more victories in the new season.',
    content: 'Full article content...',
    category: 'PUBG News',
    author: 'SnipeKing',
    author_avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=sniper',
    published_at: '2026-06-17T16:00:00Z',
    thumbnail: '/pubg-thumb.png',
    read_time: 7,
    views: 9300,
    tags: ['PUBG', 'Tips', 'Strategy', 'Chicken Dinner'],
    featured: false,
  },
  {
    id: '6',
    title: 'PUBG x Lamborghini Collab: Exclusive Vehicle Skins Leaked',
    slug: 'pubg-lamborghini-collab-skins-leaked',
    excerpt: 'Dataminers have uncovered files suggesting a massive Lamborghini collaboration bringing hyper-car skins and themed cosmetics.',
    content: 'Full article content...',
    category: 'Leaks & Rumors',
    author: 'LeakHunter',
    author_avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=leakhunter',
    published_at: '2026-06-16T20:00:00Z',
    thumbnail: '/pubg-thumb.png',
    read_time: 3,
    views: 34500,
    tags: ['PUBG', 'Leak', 'Collaboration', 'Lamborghini'],
    featured: false,
  },
];

export const MOCK_ACCOUNTS = [
  {
    id: 'acc-1',
    game: 'eFootball',
    title: 'Epic eFootball Account — Level 83',
    description: 'Top-tier account with 6 Legendary Iconic Moment players including peak Messi and Ronaldo. 500k+ GP balance.',
    image: '/account-efootball.png',
    level: 83,
    rating: 4.9,
    price: 89,
    currency: 'USD',
    rare_items: ['Iconic Messi', 'Iconic Ronaldo', 'Epic Neymar', '3x Legend Packs'],
    seller: 'ProSeller_GZ',
    seller_rating: 4.8,
    seller_sales: 127,
    featured: true,
    badge: 'HOT',
    created_at: '2026-06-20T00:00:00Z',
    verified: true,
  },
  {
    id: 'acc-2',
    game: 'eFootball',
    title: 'Mid-Tier Starter Account — Level 45',
    description: 'Great starter account with a solid squad, 150k GP, and Division 3 rank. Perfect for new players.',
    image: '/account-efootball.png',
    level: 45,
    rating: 4.5,
    price: 29,
    currency: 'USD',
    rare_items: ['Epic Mbappé', '2x Super Packs', 'Skill Trainer x10'],
    seller: 'AccountHub',
    seller_rating: 4.6,
    seller_sales: 89,
    featured: false,
    badge: 'NEW',
    created_at: '2026-06-21T00:00:00Z',
    verified: true,
  },
  {
    id: 'acc-3',
    game: 'PUBG',
    title: 'PUBG Gold Account — Season 28 Conqueror',
    description: 'Former Conqueror account with 450+ skins, rare outfits, and exclusive event items. Never compromised.',
    image: '/pubg-thumb.png',
    level: 120,
    rating: 4.7,
    price: 120,
    currency: 'USD',
    rare_items: ['Conqueror Frame', '450+ Skins', 'Mythic M416', 'Rare Pan'],
    seller: 'PUBGPro',
    seller_rating: 4.9,
    seller_sales: 54,
    featured: true,
    badge: 'FEATURED',
    created_at: '2026-06-18T00:00:00Z',
    verified: true,
  },
  {
    id: 'acc-4',
    game: 'PUBG',
    title: 'PUBG Silver Account — Season 30',
    description: 'Clean Silver account with 120 skins and full inventory. Great value for entry-level ranked play.',
    image: '/pubg-thumb.png',
    level: 65,
    rating: 4.3,
    price: 45,
    currency: 'USD',
    rare_items: ['120+ Skins', 'Legendary Crate x5', 'BP 2 Million'],
    seller: 'GamingStore',
    seller_rating: 4.4,
    seller_sales: 210,
    featured: false,
    badge: null,
    created_at: '2026-06-19T00:00:00Z',
    verified: true,
  },
  {
    id: 'acc-5',
    game: 'eFootball',
    title: 'Ultimate Dream Team — Level 99 MAX',
    description: 'Maxed-out account featuring every Iconic Moment player available. The ultimate collector dream.',
    image: '/account-efootball.png',
    level: 99,
    rating: 5.0,
    price: 299,
    currency: 'USD',
    rare_items: ['ALL Iconic Moment Players', '1M+ GP', 'Max Level Squad', '50+ Legend Packs'],
    seller: 'EliteAccounts',
    seller_rating: 5.0,
    seller_sales: 31,
    featured: true,
    badge: 'RARE',
    created_at: '2026-06-15T00:00:00Z',
    verified: true,
  },
  {
    id: 'acc-6',
    game: 'PUBG',
    title: 'PUBG Ultimate Conqueror — Season 32',
    description: 'Current Season 32 Conqueror with top 100 global rank. All exclusive cosmetics included.',
    image: '/pubg-thumb.png',
    level: 200,
    rating: 4.9,
    price: 199,
    currency: 'USD',
    rare_items: ['Top 100 Global', 'Season 32 Conqueror', '600+ Skins', 'Mythic Kar98'],
    seller: 'TopRanked',
    seller_rating: 4.8,
    seller_sales: 18,
    featured: true,
    badge: 'HOT',
    created_at: '2026-06-21T00:00:00Z',
    verified: true,
  },
];

export const MOCK_GIVEAWAYS = [
  {
    id: 'gv-1',
    title: 'Win a Full eFootball Legendary Account',
    description: 'Enter for a chance to win a premium eFootball account packed with all 6 Iconic Moment Legends!',
    prize: 'Legendary eFootball Account (Value: $89)',
    prize_value: 89,
    image: '/account-efootball.png',
    ends_at: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(), // 3 days
    entries: 1842,
    max_entries: 5000,
    requirements: ['Follow @Gamezeweno on Twitter', 'Like & Retweet the giveaway post', 'Comment your eFootball username'],
    status: 'active',
    badge: 'ENDING SOON',
  },
  {
    id: 'gv-2',
    title: 'PUBG Conqueror Account Giveaway',
    description: 'Win a Season 32 Conqueror PUBG account with 600+ exclusive skins and mythic items!',
    prize: 'PUBG Conqueror Account (Value: $199)',
    prize_value: 199,
    image: '/pubg-thumb.png',
    ends_at: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(), // 7 days
    entries: 3241,
    max_entries: 10000,
    requirements: ['Subscribe to Gamezeweno YouTube', 'Follow on Instagram', 'Share the giveaway post', 'Join Discord server'],
    status: 'active',
    badge: 'HOT',
  },
  {
    id: 'gv-3',
    title: '$50 Gaming Gift Card Giveaway',
    description: 'Win a $50 PlayStation Store / Steam gift card. Spend it on any game you love!',
    prize: '$50 Gift Card',
    prize_value: 50,
    image: '/giveaway-prize.png',
    ends_at: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(), // 14 days
    entries: 892,
    max_entries: 3000,
    requirements: ['Follow @Gamezeweno on Twitter', 'Subscribe to Newsletter'],
    status: 'active',
    badge: 'NEW',
  },
];

export const PAST_WINNERS = [
  { id: 1, username: 'DragonSlayer99', prize: 'eFootball Epic Account', date: '2026-06-01', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=dragon' },
  { id: 2, username: 'NightOwl_PK', prize: 'PUBG Gold Account', date: '2026-05-15', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=nightowl' },
  { id: 3, username: 'GamingKing_ZW', prize: '$50 Gift Card', date: '2026-05-01', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=king' },
  { id: 4, username: 'ProPlayer_X', prize: 'eFootball Level 80 Account', date: '2026-04-20', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=prox' },
];

export const GAMING_STATS = {
  total_articles: 248,
  accounts_sold: 1340,
  active_giveaways: 3,
  registered_users: 28500,
};
